version: '3.4'
services:

  scalacassandra:
    image: scalacassandra:<localBuild>
    environment:
      cassandra_host: cassandra
      startup_linger_seconds: 20
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:3.11.9
    ports:
      - 9042:9042
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
