pipeline {
    agent any

    stages {

        stage('Run all tests') {
            steps {
                sh '''#!/bin/bash
                	echo "Testing code..."
                	./sbt runAllTests
                	echo "Done testing"
         		'''
            }
        }

        stage('Deploy') {
            steps {
                sh '''#!/bin/bash
                    echo "Redeploying the app ..."
                    ./sbt redeployApp
                    echo "App has been deployed"
                '''
            }
        }
    }
}